# Site settings
title: Vincent van Daal
description: Vincent van Daal is a Linux Engineer and blogs about tech.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/"
url: "https://vincentvandaal.github.io"
paginate: 5
remote_theme: samanyougarg/hanuman

# Social
twitter: vvandaal
github:  vincentvandaal

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
- jekyll-paginate
